# Generated by Django 4.1.3 on 2022-12-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_user', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(max_length=200, null=True, upload_to='media/'),
        ),
    ]
