# Generated by Django 4.1.3 on 2022-11-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='event_id',
        ),
    ]
