# Generated by Django 4.1.3 on 2022-12-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('code', models.IntegerField(max_length=200)),
            ],
        ),
    ]
