# Generated by Django 4.1.3 on 2022-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
