# Generated by Django 3.0.5 on 2022-10-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20221017_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('frame_width', models.IntegerField(max_length=100)),
                ('frame_height', models.IntegerField(max_length=100)),
                ('genre', models.CharField(max_length=200)),
                ('fee', models.IntegerField(max_length=200)),
                ('img_path', models.ImageField(upload_to='event_images')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(default='', upload_to='images')),
                ('artist_name', models.CharField(max_length=200)),
                ('size', models.IntegerField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
