# Generated by Django 3.0.5 on 2022-10-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_price',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
