# Generated by Django 3.0.5 on 2022-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20221017_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_price',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
