# Generated by Django 3.0.5 on 2022-10-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_image_id'),
        ('events', '0018_auto_20221017_2214'),
    ]

    operations = [
    ]
