# Generated by Django 4.1.1 on 2022-11-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("events", "0023_users_delete_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="Users", new_name="User",),
    ]
