# Generated by Django 4.1.1 on 2022-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        (
            "events",
            "0025_delete_organization_user_isadmin_user_isorganization_and_more",
        ),

    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="isAdmin", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user", name="isUser", field=models.BooleanField(default=False),
        ),
    ]
