# Generated by Django 4.1.3 on 2022-11-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_user_isadmin_alter_user_isuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
