# Generated by Django 4.1.3 on 2022-11-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.RemoveField(
            model_name='image',
            name='price',
        ),
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
    ]
