# Generated by Django 4.1.3 on 2022-11-11 16:31

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_remove_image_artist_name_remove_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='event',
            name='frame_height',
        ),
        migrations.RemoveField(
            model_name='event',
            name='frame_width',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img_price',
        ),
        migrations.AddField(
            model_name='image',
            name='fee',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to=events.models.get_image_filename),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='img_price',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
