# Generated by Django 4.1.3 on 2022-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_image_frame_height_image_frame_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='fee',
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
    ]
