# Generated by Django 4.1.3 on 2022-11-14 07:44

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_remove_image_fee_event_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=events.models.get_image_filename, verbose_name='Image'),
        ),
    ]
